"""
 Functions to read in the projected frequencies generated by ProjRot
"""


def rpht_output(output_str):
    """ Parses ProjRot frequency output file strings for the
        projected vibrational frequencies, sorted in ascending order.

        Works for the output of both
            (1) rotation-translation projections and
            (2) rotation-translation/hindered-rotor projections.

        :param output_str: string of lines of ProjRot output file
        :type output_str: str
        :rtype: (list(float), list(float)
    """

    # Read the file and read in the non-zero frequencies
    freqs = []
    for line in output_str.splitlines():
        line = line.strip()
        if line != '':
            freqs.append(float(line))

    # Build lists for the real and imaginary frequencies
    real_freqs = []
    imag_freqs = []
    for freq in freqs:
        # Ignore zeros and grab the negative vals from projrot out_str
        if freq != 0.0:
            if freq > 0.0:
                real_freqs.append(freq)
            else:
                imag_freqs.append(-1.0*freq)

    # Sort imaginary freqeuncies in descending order
    imag_freqs.sort(reverse=True)

    return tuple(sorted(real_freqs)), tuple(sorted(imag_freqs))
